#WORK IN PROGRESS
- name: Install and configure an Orthanc DICOM server running inside a Docker container.
  hosts: localhost
  gather_facts: false
  vars: 
    container_name: dicom_container
  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
    #- name: Install Docker
    #- name: Configure Orthanc
    #- name: Run Orthanc container
